name: Cache Clear

on: workflow_dispatch

jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - uses: snnaplab/delete-branch-cache-action@v1
      - name: Docker cleanup commands
        run: |
          docker system prune -f
          docker volume prune -f
          docker image prune -f
